import java_cup.runtime.*;
import java.util.ArrayList;

parser code {:

    public SymbolsTable tabla = new SymbolsTable();

    private int errores_sintacticos = 0;
    public void syntax_error(Symbol s) {
        errores_sintacticos++;
        System.out.println("Error sintáctico: en la línea " + (s.left + 1) + ", columna " + (s.right + 1) + ". Valor no esperado: '" + s.value + "'");
    }
    public void unrecovered_syntax_error(Symbol s) {
        errores_sintacticos++;
        System.out.println("Error sintáctico irrecuperable: en la línea " + (s.left + 1) + ", columna " + (s.right + 1) + ". valor: '" + s.value + "'");
    }
    public int get_errores_sintacticos() {
        return errores_sintacticos;
    }

    private int errores_semanticos = 0;
    public void semantic_error(String mensaje) {
        errores_semanticos++;
        System.out.println(mensaje);
    }
    public int get_errores_semanticos() {
        return errores_semanticos;
    }
    public void agregar_simbolo(Symbols s) {
        boolean simbolo_agregado = tabla.agregar_simbolo(s);
        if (!simbolo_agregado) {
            if (s.getCategoria().equals("parametro")) {
                semantic_error("Error semántico: en línea " + s.getFila() + ", columna " + s.getColumna() + ": parametro '" + s.getNombre() + "'" + " es un duplicado");
            } else {
                semantic_error("Error semántico: en línea " + s.getFila() + ", columna " + s.getColumna() + ": variable '" + s.getNombre() + "'" + " no puede ser declaro en este scope porque ese nombre se usa para definir una variable o un parámetro");
            }
        }
    }
    public boolean agregar_funcion(Symbols s) {
        boolean funcion_agregada = tabla.agregar_funcion(s);
        if (!funcion_agregada) {
            semantic_error("Error semántico: en línea " + s.getFila() + ", columna " + s.getColumna() + ": la función '" + s.getNombre() + "' ya fue declarada");
        }
        return funcion_agregada;
    }

    /* auxiliares para el manejo de arreglos y funciones */
    public Arreglos arreglos = new Arreglos();
    public Funciones funciones = new Funciones();
:}

/* ── Terminales ── */
terminal INT, FLOAT, CHAR, STRING, BOOL, EMPTY;
terminal TRUE, FALSE;
terminal IF, ELSE, DO, WHILE;
terminal SWITCH, CASE, DEFAULT, BREAK, RETURN;
terminal CIN, COUT, MAIN;

terminal LESS_T, LESS_TE, GREATHER_T, GREATHER_TE, EQUAL, N_EQUAL;
terminal INCREMENT, DECREMENT;
terminal PLUS, MINUS, MULT, DIV, MOD, POW;
terminal AND, OR, NOT;
terminal ASSIGN;
terminal BLOCK_START, BLOCK_END;
terminal PAREN_OPEN, PAREN_CLOSE;
terminal INDEX_START, INDEX_END;
terminal SEPARATOR, COMMA, END_EXPR, COLON;

terminal String ID;
terminal String INT_LITERAL, FLOAT_LITERAL, FRAC_LITERAL, EXP_LITERAL, STRING_LITERAL, CHAR_LITERAL;

/* ── No terminales ── */
non terminal programa;
non terminal main;
non terminal lista_funciones;
non terminal crear_funcion;
non terminal opt_parametros;
non terminal lista_parametros;
non terminal parametro;
non terminal lista_sentencias;
non terminal sentencia;
non terminal crear_variable;
non terminal asignar_variable;
non terminal crear_arreglo;
non terminal modificar_arreglo;
non terminal String opt_asignacion_variable;
non terminal opt_asignacion_arreglo;
non terminal fila_arreglo;
non terminal lista_filas;
non terminal lista_num_arreglo;
non terminal elementos_arreglo;
non terminal sentencia_if;
non terminal opt_else;
non terminal sentencia_do_while;
non terminal sentencia_switch;
non terminal lista_casos;
non terminal caso;
non terminal opt_default;
non terminal sentencia_return;
non terminal sentencia_break;
non terminal cin;
non terminal cout;
non terminal String llamada_funcion;
non terminal ArrayList<String> opt_args;
non terminal ArrayList<String> lista_args;
non terminal String acceso_arreglo;
non terminal String tipo_dato;
non terminal String expresion;
non terminal String expresion_disyuncion;
non terminal String expresion_conjuncion;
non terminal String expresion_igualdad;
non terminal String expresion_relacional;
non terminal String expresion_suma;
non terminal String expresion_multiplicacion;
non terminal String expresion_potencia;
non terminal String expresion_unaria;
non terminal String expresion_primaria;
non terminal String literal;
non terminal Numero literal_numerico;
non terminal String literal_caso;
non terminal opt_lista_sentencias;
non terminal guardia_break;

start with programa;

/*  programa  */
programa ::=  lista_funciones main;

lista_funciones ::= | lista_funciones crear_funcion;

main ::= EMPTY SEPARATOR MAIN PAREN_OPEN PAREN_CLOSE {: parser.tabla.abrir_scope_funcion("__main__"); :} BLOCK_START opt_lista_sentencias BLOCK_END {: parser.tabla.cerrar_scope(); :};

/*  funciones  */
crear_funcion ::= tipo_dato:t SEPARATOR ID:id
{:
    Symbols funcion = new Symbols(id, "funcion", t, idleft + 1, idright + 1);

    boolean funcion_agregada = parser.agregar_funcion(funcion);
    parser.funciones.declaracion_valida = funcion_agregada;
    if (funcion_agregada) {
        parser.tabla.abrir_scope_funcion(id);
    }
:}
PAREN_OPEN opt_parametros PAREN_CLOSE
{:
    if (parser.funciones.declaracion_valida) {
        Symbols funcion = parser.tabla.buscar_funcion(id);
        if (funcion != null) {
            funcion.setCantidadParametros(parser.funciones.parametros_actuales);
            for (String tipo : parser.funciones.tipos_parametros_actuales) {
                funcion.agregarTipoParametro(tipo);
            }
        }
    }
:}
BLOCK_START opt_lista_sentencias BLOCK_END
{:
    if (parser.funciones.declaracion_valida) {
        parser.tabla.cerrar_scope();
    }
:};

opt_parametros ::=
{:
    parser.funciones.parametros_actuales = 0;
    parser.funciones.tipos_parametros_actuales.clear();
    parser.funciones.declaracion_valida = true;
:} | lista_parametros;

lista_parametros ::= parametro {: parser.funciones.parametros_actuales = 1; :} | lista_parametros COMMA parametro {: parser.funciones.parametros_actuales++; :};

parametro ::= tipo_dato:t SEPARATOR ID:id
{: 
    if (parser.funciones.declaracion_valida) {
        parser.funciones.tipos_parametros_actuales.add(t);
        parser.agregar_simbolo(new Symbols(id, "parametro", t, idleft + 1, idright + 1));
    }
:};

/*  tipos  */
tipo_dato ::= INT {: RESULT = "int"; :} | FLOAT {: RESULT = "float"; :} | CHAR {: RESULT = "char"; :} | STRING {: RESULT = "string"; :} | BOOL {: RESULT = "bool"; :};

/*  sentencias  */
opt_lista_sentencias ::= | lista_sentencias | error BLOCK_END;

lista_sentencias ::= sentencia | lista_sentencias sentencia;

guardia_break ::=
{:
    if (parser.tabla.hay_break_activo()) {
        int linea  = parser.tabla.get_linea_break_activo();
        int columna = parser.tabla.get_columna_break_activo();
        parser.semantic_error("Error semántico en línea " + linea + ", columna " + columna + ": código inalcanzable después de 'break'.");
    }
:};

sentencia ::= guardia_break crear_variable | guardia_break asignar_variable | guardia_break crear_arreglo | guardia_break modificar_arreglo | guardia_break sentencia_if | guardia_break sentencia_do_while | guardia_break sentencia_switch | guardia_break sentencia_return | sentencia_break | guardia_break cin | guardia_break cout | guardia_break expresion END_EXPR | error END_EXPR;

/*  variables  */
crear_variable ::= tipo_dato:t SEPARATOR ID:id opt_asignacion_variable:e END_EXPR 
{: 
    if (e != null && !t.equals(e)) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": no se puede asignar un valor de tipo '" + e + "' a una variable de tipo '" + t + "'");
    }
    parser.agregar_simbolo(new Symbols(id, "variable", t, idleft + 1, idright + 1)); 
:};

opt_asignacion_variable ::= {: RESULT = null; :}| ASSIGN expresion:e {: RESULT = e; :};

asignar_variable ::= ID:id ASSIGN expresion END_EXPR
{:
    Symbols s = parser.tabla.buscar_simbolo(id);
    if (s == null) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": variable '" + id + "'" + " no esta declarada");
    }
:};

/*  arreglos  */
crear_arreglo ::= tipo_dato:t SEPARATOR ID:id INDEX_START literal_numerico:cf INDEX_END INDEX_START literal_numerico:cc INDEX_END
{: 
    parser.arreglos.reiniciar();
    parser.arreglos.tipo_arreglo_actual = t;

    /* validar el tipo del arreglo */
    if (!t.equals("int") && !t.equals("float")) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": no es posible crear un arreglo de tipo '" + t + "'. Los arreglos solo pueden ser de tipo int o float");
        parser.arreglos.arreglo_valido = false;
    }

    /* validar el tipo de las dimensiones */
    if (parser.arreglos.arreglo_valido) {
        if (!cf.getTipo().equals("int") || !cc.getTipo().equals("int")) {
            parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": las dimensiones de un arreglo solo pueden ser enteros");
            parser.arreglos.arreglo_valido = false;
        }
    }

    /* guardar dimensiones */
    if (parser.arreglos.arreglo_valido) {
        parser.arreglos.cantidad_filas_esperadas = Integer.parseInt(cf.getValor());
        parser.arreglos.cantidad_columnas_esperadas = Integer.parseInt(cc.getValor());
    }
:}

opt_asignacion_arreglo END_EXPR
{: 
    if (parser.arreglos.arreglo_valido) {
        /* validar filas*/
        if (parser.arreglos.filas_encontradas > 0 && parser.arreglos.filas_encontradas != parser.arreglos.cantidad_filas_esperadas) {
            parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": el arreglo tiene " + parser.arreglos.filas_encontradas + " filas pero se declararon " + parser.arreglos.cantidad_filas_esperadas);
            parser.arreglos.arreglo_valido = false;
        }
    }
    if (parser.arreglos.arreglo_valido) {
        parser.agregar_simbolo(new Symbols(id, "arreglo", t, idleft + 1, idright + 1));
    }
:};

opt_asignacion_arreglo ::= | ASSIGN elementos_arreglo;

elementos_arreglo ::= BLOCK_START lista_filas BLOCK_END;

lista_filas ::= fila_arreglo {: parser.arreglos.filas_encontradas = 1; :} | lista_filas COMMA fila_arreglo {: parser.arreglos.filas_encontradas++; :};

fila_arreglo ::= BLOCK_START literal_numerico:n lista_num_arreglo BLOCK_END
{: 
    parser.arreglos.columnas_encontradas++;
    /* validar columnas */
    if (parser.arreglos.arreglo_valido) {
        if (parser.arreglos.columnas_encontradas != parser.arreglos.cantidad_columnas_esperadas) {
            int fila_actual = parser.arreglos.filas_encontradas + 1;
            parser.semantic_error("Error semántico en línea " + (nleft + 1) + ", columna " + (nright + 1) + ": la fila " + fila_actual + " tiene " + parser.arreglos.columnas_encontradas + " elementos pero se esperaban " + parser.arreglos.cantidad_columnas_esperadas);
            parser.arreglos.arreglo_valido = false;
        }
    }
    /* validar tipo de los elementos */
    if (parser.arreglos.arreglo_valido) {
        if (parser.arreglos.tipo_arreglo_actual.equals("int") && !n.getTipo().equals("int")) {
            parser.semantic_error("Error semántico en línea " + (nleft + 1) + ", columna " + (nright + 1) + ": los elementos del arreglo deben ser de tipo int");
            parser.arreglos.arreglo_valido = false;
        }
        if (parser.arreglos.tipo_arreglo_actual.equals("float") && !n.getTipo().equals("float")) {
            parser.semantic_error("Error semántico en línea " + (nleft + 1) + ", columna " + (nright + 1) + ": los elementos del arreglo deben ser de tipo float");
            parser.arreglos.arreglo_valido = false;
        }
    }
    parser.arreglos.columnas_encontradas = 0;
:};

lista_num_arreglo ::= | lista_num_arreglo COMMA literal_numerico:n
{: 
    if (parser.arreglos.arreglo_valido) {
        parser.arreglos.columnas_encontradas++;
        /* validar tipo de los elementos */
        if (parser.arreglos.tipo_arreglo_actual.equals("int") && !n.getTipo().equals("int")) {
            parser.semantic_error("Error semántico en línea " + (nleft + 1) + ", columna " + (nright + 1) + ": los elementos del arreglo deben ser de tipo int");
            parser.arreglos.arreglo_valido = false;
        }
        /* validar tipo de los elementos */
        if (parser.arreglos.tipo_arreglo_actual.equals("float") && !n.getTipo().equals("float")) {
            parser.semantic_error("Error semántico en línea " + (nleft + 1) + ", columna " + (nright + 1) + ": los elementos del arreglo deben ser de tipo float");
            parser.arreglos.arreglo_valido = false;
        }
    }
:};

modificar_arreglo ::= acceso_arreglo ASSIGN expresion END_EXPR;

acceso_arreglo ::= ID:id INDEX_START literal_numerico:nf INDEX_END INDEX_START literal_numerico:nc INDEX_END
{:
    Symbols s = parser.tabla.buscar_simbolo(id);
    if (s == null) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": arreglo '" + id + "' no declarado");
        RESULT = "error";
    } else if (!s.getCategoria().equals("arreglo")) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": '" + id + "' no es un arreglo");
    }
    else {
        RESULT = s.getTipo();

        /* validar fila */
        if (!nf.getTipo().equals("int")) {
            parser.semantic_error("Error semántico en línea " + (nfleft + 1) + ", columna " + (nfright + 1) + ": el índice de fila debe ser de tipo int");
        }

        /* validar columna */
        if (!nc.getTipo().equals("int")) {
            parser.semantic_error("Error semántico en línea " + (ncleft + 1) + ", columna " + (ncright + 1) + ": el índice de columna debe ser de tipo int");
        }
    }
:};

/*  bloques de control */
sentencia_if ::= IF PAREN_OPEN expresion PAREN_CLOSE {: parser.tabla.abrir_scope("if"); :} BLOCK_START opt_lista_sentencias BLOCK_END {: parser.tabla.cerrar_scope(); :} opt_else;

opt_else ::= | ELSE {: parser.tabla.abrir_scope("else"); :} BLOCK_START opt_lista_sentencias BLOCK_END {: parser.tabla.cerrar_scope(); :};

sentencia_do_while ::= DO {: parser.tabla.abrir_scope("do_while"); :} BLOCK_START opt_lista_sentencias BLOCK_END {: parser.tabla.cerrar_scope(); :} WHILE PAREN_OPEN expresion PAREN_CLOSE END_EXPR;

sentencia_switch ::= SWITCH PAREN_OPEN expresion PAREN_CLOSE {: parser.tabla.abrir_scope("switch"); :} BLOCK_START lista_casos opt_default BLOCK_END {: parser.tabla.cerrar_scope(); :};

lista_casos ::= caso | lista_casos caso;

caso ::= CASE SEPARATOR literal_caso:t COLON
{:
    if (!t.equals("int") && !t.equals("char")) {
        parser.semantic_error("Error semántico en línea " + (tleft + 1) + ", columna " + (tright + 1) + ": '" + t + "' no es un caso válido, solo se permiten int o char");
    }
    parser.tabla.abrir_scope("case");
:}
opt_lista_sentencias
{:
    parser.tabla.cerrar_scope();
:};

opt_default ::=
| DEFAULT COLON {: parser.tabla.abrir_scope("default"); :} opt_lista_sentencias {: parser.tabla.cerrar_scope(); :};

sentencia_return ::= RETURN:r SEPARATOR expresion END_EXPR
{:
    if (parser.tabla.return_ya_declarado()) {
        parser.semantic_error("Error semántico en línea " + (rleft + 1) + ", columna " + (rright + 1) + ": 'return' duplicado en el mismo bloque, solo se permite un return por bloque.");
    } else {
        parser.tabla.marcar_return();
    }
:}
| RETURN error END_EXPR;

sentencia_break ::= BREAK:b END_EXPR
{:
    if (parser.tabla.break_ya_declarado()) {
        parser.semantic_error("Error semántico en línea " + (bleft + 1) + ", columna " + (bright + 1) + ": 'break' duplicado, solo se permite un break por bloque.");
    } else {
        parser.tabla.marcar_break_contenedor(bleft + 1, bright + 1);
    }
    parser.tabla.marcar_break_local(bleft + 1, bright + 1);
:}
| BREAK error END_EXPR;

/*  CIN / COUT */
cin ::= CIN PAREN_OPEN ID:id PAREN_CLOSE END_EXPR 
{:
    Symbols s = parser.tabla.buscar_simbolo(id);

    if (s == null) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": variable '" + id + "' no declarada");
    }
    else {
        String tipo = s.getTipo();
        if (!tipo.equals("int") && !tipo.equals("float")) {
            parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": cin solo puede leer variables de tipo int o float");
        }
    }
:};

cout ::= COUT PAREN_OPEN expresion:e PAREN_CLOSE END_EXPR;

/*  llamada a funcion */
llamada_funcion ::= ID:id PAREN_OPEN opt_args:args PAREN_CLOSE
{:
    Symbols s = parser.tabla.buscar_funcion(id);
    if (s == null) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": función '" + id + "' no declarada");
        RESULT = "error";
    }
    else if (!s.getCategoria().equals("funcion")) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": '" + id + "' no es una función");
        RESULT = "error";
    }
    else {
        if (s.getCantidadParametros() != args.size()) {
            parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": la función '" + id + "' esperaba " + s.getCantidadParametros() + " parámetros pero recibió " + args.size());
        } else {
            for (int i = 0; i < args.size(); i++) {
                String tipo_esperado = s.getTiposParametros().get(i);
                String tipo_recibido = args.get(i);
                if (!tipo_esperado.equals(tipo_recibido)) {
                    parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": en la llamada a '" + id + "' el parámetro " + (i + 1) + " esperaba un valor de tipo '" + tipo_esperado + "' pero recibió '" + tipo_recibido + "'");
                    break;
                }
            }
        }
        RESULT = s.getTipo();
    }
:};

opt_args ::= {: RESULT = new ArrayList<String>(); :} | lista_args:l 
{:
    RESULT = l;
:};

lista_args ::= expresion:e
{: 
    ArrayList<String> tipos = new ArrayList<String>();
    tipos.add(e);
    RESULT = tipos;
:} | lista_args:l COMMA expresion:e 
{: 
    l.add(e);
    RESULT = l;
:};

/*  expresiones */
expresion ::= expresion_disyuncion:e {: RESULT = e; :};

expresion_disyuncion ::= expresion_conjuncion:e {:RESULT = e; :} | expresion_disyuncion:e1 OR expresion_conjuncion:e2 {: RESULT = "bool"; :};

expresion_conjuncion ::= expresion_igualdad:e {: RESULT = e; :} | expresion_conjuncion:e1 AND expresion_igualdad:e2 {: RESULT = "bool"; :};

expresion_igualdad ::= expresion_relacional:e {: RESULT = e; :} | EQUAL PAREN_OPEN expresion:e1 COMMA expresion:e2 PAREN_CLOSE {: RESULT = "bool"; :} | N_EQUAL PAREN_OPEN expresion:e1 COMMA expresion:e2 PAREN_CLOSE {: RESULT = "bool"; :};

expresion_relacional ::= expresion_suma:e {: RESULT = e; :} | LESS_T PAREN_OPEN expresion:e1 COMMA expresion:e2 PAREN_CLOSE {: RESULT = "bool"; :} | LESS_TE PAREN_OPEN expresion:e1 COMMA expresion:e2 PAREN_CLOSE {: RESULT = "bool"; :} | GREATHER_T PAREN_OPEN expresion:e1 COMMA expresion:e2 PAREN_CLOSE {: RESULT = "bool"; :} | GREATHER_TE PAREN_OPEN expresion:e1 COMMA expresion:e2 PAREN_CLOSE {: RESULT = "bool"; :};

expresion_suma ::= expresion_multiplicacion:e {: RESULT = e; :} | expresion_suma:e1 PLUS expresion_multiplicacion:e2 {: RESULT = e1; :} | expresion_suma:e1 MINUS expresion_multiplicacion:e2 {: RESULT = e1; :};

expresion_multiplicacion ::= expresion_potencia:e {: RESULT = e; :} | expresion_multiplicacion:e1 MULT expresion_potencia:e2 {: RESULT = e1; :} | expresion_multiplicacion:e1 DIV expresion_potencia:e2 {: RESULT = e1; :} | expresion_multiplicacion:e1 MOD expresion_potencia:e2 {: RESULT = e1; :};

expresion_potencia ::= expresion_unaria:e {: RESULT = e; :} | expresion_unaria:e1 POW expresion_potencia:e2 {: RESULT = e1; :};

expresion_unaria ::= expresion_primaria:e {: RESULT = e; :} | MINUS expresion_unaria:e {: RESULT = e; :} | NOT expresion_unaria:e {: RESULT = "bool"; :} | INCREMENT ID:id
{:
    Symbols s = parser.tabla.buscar_simbolo(id);

    if (s == null) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": variable '" + id + "' no declarada");
        RESULT = "error";
    } else {
        if (!s.getTipo().equals("int") && !s.getTipo().equals("float")) {
            parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": el operador '++' solo puede aplicarse a variables de tipo int o float");
            RESULT = "error";
        } else {
            RESULT = s.getTipo();
        }
    }
:} | DECREMENT ID:id
{:
    Symbols s = parser.tabla.buscar_simbolo(id);

    if (s == null) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": variable '" + id + "' no declarada");
        RESULT = "error";
    } else {
        if (!s.getTipo().equals("int") && !s.getTipo().equals("float")) {
            parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": el operador '--' solo puede aplicarse a variables de tipo int o float");
            RESULT = "error";
        } else {
            RESULT = s.getTipo();
        }
    }
:};

expresion_primaria ::= literal:l {: RESULT = l; :} | ID:id
{:
    Symbols s = parser.tabla.buscar_simbolo(id);
    if (s == null) {
        parser.semantic_error("Error semántico en línea " + (idleft + 1) + ", columna " + (idright + 1) + ": variable '" + id + "' no declarada");
        RESULT = "error";
    } else {
        RESULT = s.getTipo();
    }
:} | llamada_funcion:f {: RESULT = f; :} | acceso_arreglo | PAREN_OPEN expresion PAREN_CLOSE;

/*  literales */
literal ::= literal_numerico:l {: RESULT = l.getTipo(); :} | STRING_LITERAL {: RESULT = "string"; :} | CHAR_LITERAL {: RESULT = "char"; :} | TRUE {: RESULT = "bool"; :} | FALSE {: RESULT = "bool"; :}; 

literal_numerico ::= INT_LITERAL:i {: RESULT = new Numero("int", i); :} | FLOAT_LITERAL:f {: RESULT = new Numero("float", f); :} | FRAC_LITERAL:f {: RESULT = new Numero("float", f); :} | EXP_LITERAL:e {: RESULT = new Numero("float", e); :};

literal_caso ::= literal_numerico:l {: RESULT = l.getTipo(); :} | CHAR_LITERAL {: RESULT = "char"; :};